# version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: vt-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - vt-network
    env_file:
      - ./frontend/.env

  bacapkend:
    build: ./backend
    container_name: vt-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - redis
    env_file:
      - ./backend/.env
    
      
    networks:
      - vt-network

  redis:
    image: redis:7
    container_name: vt-redis
    ports:
      - "6379:6379"
    networks:
      - vt-network

networks:
  vt-network:
    driver: bridge

volumes:
#   pgdata:
  redis_data: