# version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: vault_tracker-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - vault_tracker_network

  backend:
    build: ./backend
    container_name: vault_tracker-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}  # Pass the password from .env

      
    networks:
      - vault_tracker_network

  redis:
    image: redis:7
    container_name: vault_tracker-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} >/dev/null 2>&1
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}  # Set in .env

    volumes:
      - redis_data:/data
    networks:
      - vault_tracker_network

networks:
  vault_tracker_network:
    driver: bridge

volumes:
  pgdata:
  redis_data: