# version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: vault_tracker-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: vault_tracker-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - redis
    env_file:
      - .env


  redis:
    image: redis:7
    container_name: vault_tracker-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
