name: Python Deploy

on:
    push:
        branches: [dev]

jobs:
    test-ssh-connection:
        runs-on: ubuntu-latest
        steps:
            - name: Test Droplet connection
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                password: ${{  secrets.SSH_PASSWORD }}
                port: 22
                script: |
                    whoami
                    echo "Github Action was here"
                    exit
    
    deploy-python:
        runs-on: ubuntu-latest
        needs: test-ssh-connection
        steps:
            - name: Deploy using ssh
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                password: ${{  secrets.SSH_PASSWORD }}
                port: 22
                script: |
                    cd Desktop/Vault_Tracker/backend
                    git fetch origin
                    git checkout dev
                    git pull
                    ./scripts/docker-build-run.sh
    deploy-next:
        runs-on: ubuntu-latest
        needs: deploy-python
        steps:
            - name: Deploy using ssh
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                password: ${{  secrets.SSH_PASSWORD }}
                port: 22
                script: |
                    cd Desktop/Vault_Tracker/frontend
                    git fetch origin
                    git checkout dev
                    git pull
                    docker build -t vt-next:latest .
                    docker stop vt-nextapp || true
                    docker rm vt-nextapp || true
                    docker run -d --name vt-nextapp -p 3000:3000 vt-next:latest