name: Next Deploy

on:
    workflow_run:
        workflows: ["Python Deploy"]
        types:
            - completed
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy using ssh
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                password: ${{  secrets.SSH_PASSWORD }}
                port: 22
                script: |
                    cd Desktop/Vault_Tracker/frontend
                    git fetch origin
                    git checkout dev
                    git pull
                    docker build -t vt-next:latest .
                    docker stop vt-nextapp || true
                    docker rm vt-nextapp || true
                    docker run -d --name vt-nextapp -p 3000:3000 vt-next:latest